/**
 * Extracts the first valid JSON object from a raw string generated by an LLM.
 * Robust against trailing text or missing brackets.
 */
export function extractJSON(text) {
  const start = text.indexOf('{');
  if (start === -1) return null;
  
  let end = text.lastIndexOf('}');
  while (end > start) {
    try {
      const candidate = text.substring(start, end + 1);
      return JSON.parse(candidate);
    } catch (e) {
      // If it fails (e.g., extra '}' at the end), try the previous '}'
      end = text.lastIndexOf('}', end - 1);
    }
  }
  return null;
}

/**
 * GUARDRAIL: Anti-Hallucination
 * Small Language Models (1B) sometimes hallucinate attributes.
 * We verify that the extracted attributes actually appear in the original request.
 */
export function validateAIIntent(parsed, originalInput) {
  if (!parsed || !originalInput) return parsed;
  
  const inputLower = originalInput.toLowerCase();
  
  // Validate Color
  if (parsed.color && typeof parsed.color === 'string' && parsed.color !== 'null') {
    if (!inputLower.includes(parsed.color.toLowerCase())) {
      parsed.color = null; // Hallucination detected, suppress it
    }
  }
  
  // Validate Style
  if (parsed.style && typeof parsed.style === 'string' && parsed.style !== 'null') {
    const styleStr = parsed.style.toLowerCase().replace('-', '');
    const inputStr = inputLower.replace('-', '');
    if (!inputStr.includes(styleStr) && !inputLower.includes(parsed.style.toLowerCase())) {
      parsed.style = null; // Hallucination detected
    }
  }
  
  return parsed;
}
